### ISSUE TITLE
Investigate usage of localstack for use with DUM local integration testing

### ISSUE THREAD

**Issue by collinss-jpl** [NASA-PDS/data-upload-manager#134]
### 💡 Description

The localstack application looks promising for emulating the AWS services utilized by Data Upload Manager for the purposes of local integration testing. This ticket is to investigate installation and configuration of localstack (using a "hobbyist" license) to develop a proof of concept that can communicate with the DUM client script.

**Comment by collinss-jpl** [comment]
TODO: create a wiki page with instructions for getting up and running with localstack and deploying via terraform

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is making progress on that ticket.
But the lambda authorizer does not work in localstack. A workaround is available in localstack but not released. In the meatime, Scott is adding a flag in the deployment to ignore the authorizer in a local deployment.

**Comment by tloubrieu-jpl** [comment]
DUM terraform is not creating the staging buckets, since this is not needed in production (it is not part of the DUM component).

Depending on the development venue, interfaced components are going to be created or not.

After that is being done, @collinss-jpl will create an PR.

It sounds like the pushing the log to cloudwatch would not work with localstack. That will not be a deal breaker.
