### ISSUE TITLE
verify the node of the user against Cognito

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/data-upload-manager#18]
## 💡 Description

0. we need groups for each node
1. The cognito user will be assigned node groups (at least one).
2. The client will forward the access token to the API gateway
3. The lambda authorizer will decode the groups, and check that it matches the node as specified in the header of the request.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl 
need support from @ramesh-maddegoda to access the authorizer's log on cloudwatch

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is trying to access the header from the lambda authorizer but it does not work and Scott can not log the lambda function.

**Comment by jordanpadams** [comment]
status: working on configuring this to work through API Gateway and making sure Cognito groups are being checked. Authorizer function logging issue was actually due to issues with the function not executing. @collinss-jpl will be working on the permission rules here coming up between now and Tuesday.

**Comment by jordanpadams** [comment]
status: met with NGAP to debug issues with API Gateway and Lambda. issue still remains. tried going back from scratch and appears unsuccessful. need to loop back with Jason about why this is failing.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl spotted the configuration which was missing for the authorizer lambda to work.
